name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to match the name of your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Permissions
      run: |
        sudo chown -R $USER .
        sudo chmod -R 777 .
        
    - name: Install Dependencies
      run: |
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        gem install bundler
        bundle install

    - name: Build with Jekyll
      uses: docker://jekyll/builder:latest
      with:
        entrypoint: jekyll
        args: build --destination ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
